#!/usr/bin/env node
/**
 * Write THIRD_PARTY_NOTICES.md: every library that ships in the production
 * bundle (from package-lock.json, development tools left out) with its
 * version, licence and copyright lines, then each distinct licence text once.
 * Read from node_modules, so run `npm ci` first.
 *
 *   npm run build:notices
 */
import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { isMain } from './lib/is-main.mjs';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const read = (p) => readFileSync(path.join(ROOT, p), 'utf8');

/** The production packages named in the lockfile, by name. */
export function productionPackages(lock) {
  const out = [];
  for (const [key, meta] of Object.entries(lock.packages)) {
    if (!key || meta.dev || meta.devOptional || meta.optional) continue;
    out.push({ name: key.replace(/^.*node_modules\//, ''), dir: key, version: meta.version });
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}

const LICENSE_FILE = /^(licen[cs]e(-[a-z0-9.]+)?|copying|notice)(\.(md|txt))?$/i;
// A notice names a year or a (c) sign: "Copyright 2011 …", "Copyright (c) …", "(c) 2015 …". The Apache text's own
// "Copyright notice that is…" sentences are not notices.
const COPYRIGHT = /^\s*[*#>-]*\s*(copyright\s*(\(c\)|©|\d)|\(c\)\s*\d|©)/i;

/** The standard Apache text ends here; what follows in some packages is notices for code they bundle. */
const APACHE_END = /END OF TERMS AND CONDITIONS/i;

/** A browsable address for the many ways package.json writes a repository. */
export function repoUrl(value) {
  let url = String(value || '').trim().replace(/^git\+/, '').replace(/\.git$/, '');
  url = url.replace(/^(ssh:\/\/)?git@([^:/]+)[:/]/, 'https://$2/').replace(/^git:\/\//, 'https://').replace(/^github:/, 'https://github.com/');
  if (/^[\w.-]+\/[\w.-]+$/.test(url)) url = `https://github.com/${url}`;
  return /^https?:\/\//.test(url) ? url : '';
}

function details({ dir }) {
  const folder = path.join(ROOT, dir);
  let pkg = {};
  try {
    pkg = JSON.parse(read(`${dir}/package.json`));
  } catch {}
  const files = existsSync(folder) ? readdirSync(folder).filter((f) => LICENSE_FILE.test(f)).sort() : [];
  // dompurify ships its MPL text beside the Apache one; either may be used, and one is enough here.
  const main = files.filter((f) => !/mpl/i.test(f))[0];
  const text = main ? readFileSync(path.join(folder, main), 'utf8').replace(/\r\n/g, '\n') : '';
  const license = typeof pkg.license === 'string' ? pkg.license : pkg.license?.type || (pkg.licenses || []).map((l) => l.type).join(' OR ') || 'see package';
  return { license, repo: repoUrl(typeof pkg.repository === 'string' ? pkg.repository : pkg.repository?.url || pkg.homepage || ''), text, copyright: text.split('\n').filter((l) => COPYRIGHT.test(l)).map((l) => l.replace(/^[\s*#>-]+/, '').trim()).slice(0, 3) };
}

/** A licence text with its copyright lines and spacing removed, so the same licence given by many packages is one text. */
const normal = (text) => {
  const cut = APACHE_END.test(text) ? text.slice(0, text.search(APACHE_END) + 'END OF TERMS AND CONDITIONS'.length) : text;
  return cut.split('\n').filter((l) => !COPYRIGHT.test(l)).join('\n').replace(/\s+/g, ' ').trim();
};

export function buildNotices() {
  const lock = JSON.parse(read('package-lock.json'));
  const packages = productionPackages(lock).map((p) => ({ ...p, ...details(p) }));
  const texts = new Map(); // hash → { text, license, users: [] }
  for (const p of packages) {
    if (!p.text) continue;
    const key = createHash('sha1').update(normal(p.text)).digest('hex');
    if (!texts.has(key)) {
      const body = APACHE_END.test(p.text) ? `${p.text.slice(0, p.text.search(APACHE_END) + 'END OF TERMS AND CONDITIONS'.length).trim()}\n\n(The package's own LICENSE file goes on to list notices for code it bundles; they ship with the package.)` : p.text.trim();
      texts.set(key, { body: body.split('\n').filter((l) => !COPYRIGHT.test(l)).join('\n').replace(/\n{3,}/g, '\n\n'), license: p.license, users: [] });
    }
    texts.get(key).users.push(p.name);
  }
  const lines = [];
  lines.push('# Third-party notices', '');
  lines.push(
    "God's Eye // UAP is MIT-licensed (see [LICENSE](LICENSE)). The production bundle includes the libraries below, each under its own licence.",
    '',
    'This file is generated by `npm run build:notices` from `package-lock.json` and `node_modules`; do not edit it by hand.',
    '',
    '**Data and media are separate.** Imagery, scans, footage, text and place names come from the sources in [DATA_SOURCES.md](DATA_SOURCES.md), each under its own terms.',
    '',
    '**Fonts.** Inter and JetBrains Mono are loaded from Google Fonts at run time, under the SIL Open Font Licence 1.1.',
    '',
    `## Libraries (${packages.length})`,
    '',
    '| Package | Version | Licence | Source |',
    '|---|---|---|---|',
  );
  for (const p of packages) lines.push(`| \`${p.name}\` | ${p.version} | ${p.license.replace(/\|/g, '/')} | ${p.repo ? `<${p.repo}>` : ''} |`);
  lines.push('', '## Licence texts', '', 'Each text is given once, with the packages that use it and their copyright lines.', '');
  for (const { body, license, users } of texts.values()) {
    lines.push(`### ${license}`, '');
    for (const name of users) {
      const p = packages.find((x) => x.name === name);
      lines.push(`- \`${name}\`${p.copyright.length ? `: ${p.copyright.join('; ')}` : ''}`);
    }
    lines.push('', '```text', body, '```', '');
  }
  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}

if (isMain(import.meta.url)) {
  const out = buildNotices();
  writeFileSync(path.join(ROOT, 'THIRD_PARTY_NOTICES.md'), out);
  console.log(`THIRD_PARTY_NOTICES.md: ${out.split('\n').length} lines`);
}
